# Generated by Django 2.2.7 on 2019-11-24 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='The time it was created')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='The time when it was latestly edited')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='The time when it was deleted')),
                ('deleted', models.BooleanField(default=False, verbose_name='This record is deleted')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField(verbose_name='The content of an article')),
                ('html', models.TextField(verbose_name='The html formed content of an article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
